dist: trusty
sudo: required
language: node_js
node_js:
  - "10"
jdk:
    - oraclejdk8

before_install:
    # install Neo4j locally:
    - wget http://dist.neo4j.org/neo4j-community-3.5.6-unix.tar.gz
    - tar -xzf neo4j-community-3.5.6-unix.tar.gz
    - neo4j-community-3.5.6/bin/neo4j-admin set-initial-password admin
    - neo4j-community-3.5.6/bin/neo4j start
